### ISSUE TITLE
Document bartender client generation

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/bartended-haddock3#3]
See commit message https://github.com/i-VRESSE/bartended-haddock3/commit/5bebbd802d5cee98de4bffc888097a8ce4797178

**Comment by Peter9192** [comment]
In https://github.com/i-VRESSE/bartender/issues/13 we decided to move the example with the haddock example over to this repo. For reference, here's the documentation that was removed there:

https://github.com/i-VRESSE/bartender/blob/5689e2e9fbfbb14d750f97f975b766eafd7e1e5c/README.md?plain=1#L342-L365

**Comment by sverhoeven** [comment]
Done in 615514ec68cdab9b01d76661b5b5ca34b1fb993e
